import Head from 'next/head';
import dynamic from 'next/dynamic';
const KalidoCanvas = dynamic(() => import('./KalidoCanvas/index.page'), {ssr: false});

export default function Home() {
  return (
    <>
      <Head>
        <title>VRM Mocap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <KalidoCanvas />
      </main>
    </>
  );
}
